#Open OGL Window

/vis/open OGL

#Set Style

/vis/drawVolume
#/vis/scene/add/axes 0 0 0 10 nm

/vis/viewer/set/style surface
/vis/geometry/set/visibility World 0 false
/vis/viewer/set/viewpointVector -1 0 0
/vis/geometry/set/colour Shell 1 1 1 1 0.5
/vis/viewer/set/lightsThetaPhi 190 0

#Set Trajectories

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

#Particle Filtering

#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma

#Accumulate All Runs

/vis/scene/endOfEventAction accumulate
